import ast
import os
import re

file_path = 'alembic/versions/95929ae669b9_add_hr_and_inventory_modules.py'

with open(file_path, 'r') as f:
    content = f.read()

# We will use regex to extract the create_table and create_index blocks we care about
targets = ['warehouses', 'item_categories', 'items', 'stock_movements', 'employees', 'employee_documents', 'absences', 'payroll_slips', 'payroll_slip_lines', 'salary_advances']

import sys

def filter_statements(body_str, prefix):
    # This is a naive regex parser for alembic ops
    statements = re.findall(r"(    op\.[a-z_]+\(.*?)(?=    op\.|    # ###|$)", body_str, flags=re.DOTALL)
    
    keep_stmts = []
    for stmt in statements:
        keep = False
        for t in targets:
            if f"'{t}'" in stmt or f"'{t}_" in stmt or f"ix_{t}_" in stmt:
                keep = True
                break
        if keep:
            keep_stmts.append(stmt)
    return "".join(keep_stmts)

upgrade_match = re.search(r"def upgrade\(\) -> None:\n    # ### commands auto generated by Alembic - please adjust! ###\n(.*?)    # ### end Alembic commands ###", content, flags=re.DOTALL)
downgrade_match = re.search(r"def downgrade\(\) -> None:\n    # ### commands auto generated by Alembic - please adjust! ###\n(.*?)    # ### end Alembic commands ###", content, flags=re.DOTALL)

if upgrade_match and downgrade_match:
    up_body = upgrade_match.group(1)
    down_body = downgrade_match.group(1)
    
    new_up_body = filter_statements(up_body, "op.create_table")
    new_down_body = filter_statements(down_body, "op.drop_table")
    
    new_content = content[:upgrade_match.start(1)] + new_up_body + content[upgrade_match.end(1):downgrade_match.start(1)] + new_down_body + content[downgrade_match.end(1):]
    
    with open(file_path, 'w') as f:
        f.write(new_content)
    print("Successfully patched the migration file.")
else:
    print("Could not parse upgrade/downgrade blocks.")
