"""reconcile production schema

Revision ID: 1e006dfe187d
Revises: bay01
Create Date: 2026-07-22 16:56:38.732434+02:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "1e006dfe187d"
down_revision: str | None = "bay01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_RLS_TABLES = (
    "absences",
    "accounting_accounts",
    "accounting_journal_entries",
    "accounting_journal_items",
    "core_return_items",
    "employee_documents",
    "employees",
    "fiscal_counters",
    "item_categories",
    "items",
    "outbox_events",
    "part_reservations",
    "payroll_codes",
    "payroll_slip_lines",
    "payroll_slips",
    "purchase_orders",
    "reception_photos",
    "salary_advances",
    "service_catalog_items",
    "service_warranties",
    "spare_part_requisitions",
    "spare_part_serial_items",
    "stock_movements",
    "supplier_invoices",
    "supplier_payments",
    "task_labor_logs",
    "tenant_sequences",
    "tool_calibrations",
    "vehicle_receptions",
    "vehicle_releases",
    "warehouses",
    "work_bays",
    "workshop_purchase_order_items",
    "workshop_purchase_orders",
    "workshop_quote_items",
    "workshop_quotes",
    "workshop_staff_rates",
)

_ALREADY_RLS = {
    "absences",
    "accounting_accounts",
    "accounting_journal_entries",
    "accounting_journal_items",
    "employee_documents",
    "employees",
    "fiscal_counters",
    "item_categories",
    "items",
    "outbox_events",
    "payroll_codes",
    "payroll_slip_lines",
    "payroll_slips",
    "purchase_orders",
    "salary_advances",
    "spare_part_serial_items",
    "stock_movements",
    "supplier_invoices",
    "supplier_payments",
    "tool_calibrations",
    "warehouses",
    "workshop_staff_rates",
}


def _apply_canonical_rls(table: str) -> None:
    op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
    op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
    op.execute(
        f"CREATE POLICY tenant_isolation ON {table} "
        "USING (tenant_id::text = current_setting('app.tenant_id', true)) "
        "WITH CHECK (tenant_id::text = current_setting('app.tenant_id', true))"
    )
    op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table} TO rotas_app")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_labor_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("work_order_task_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("minutes_worked", sa.Integer(), nullable=False),
        sa.Column("hourly_rate_applied", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total_labor_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("void_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["work_order_task_id"], ["work_order_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_labor_logs_tenant_id"), "task_labor_logs", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_task_labor_logs_user_id"), "task_labor_logs", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_task_labor_logs_work_order_task_id"), "task_labor_logs", ["work_order_task_id"], unique=False
    )
    op.create_table(
        "workshop_purchase_orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("supplier_third_party_id", sa.UUID(), nullable=False),
        sa.Column("po_number", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("supplier_invoice_number", sa.String(length=120), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_third_party_id"],
            ["third_parties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "po_number", name="uq_workshop_purchase_orders_tenant_number"),
    )
    op.create_index(
        op.f("ix_workshop_purchase_orders_po_number"), "workshop_purchase_orders", ["po_number"], unique=False
    )
    op.create_index(op.f("ix_workshop_purchase_orders_status"), "workshop_purchase_orders", ["status"], unique=False)
    op.create_index(
        op.f("ix_workshop_purchase_orders_supplier_third_party_id"),
        "workshop_purchase_orders",
        ["supplier_third_party_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workshop_purchase_orders_tenant_id"), "workshop_purchase_orders", ["tenant_id"], unique=False
    )
    op.create_table(
        "core_return_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("work_order_id", sa.UUID(), nullable=False),
        sa.Column("inventory_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("serial_number", sa.String(length=120), nullable=True),
        sa.Column("evidence_photo_file_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("credit_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("supplier_third_party_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_photo_file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["inventory_id"],
            ["spare_parts_inventory.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_third_party_id"],
            ["third_parties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"],
            ["work_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_core_return_items_inventory_id"), "core_return_items", ["inventory_id"], unique=False)
    op.create_index(op.f("ix_core_return_items_status"), "core_return_items", ["status"], unique=False)
    op.create_index(op.f("ix_core_return_items_tenant_id"), "core_return_items", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_core_return_items_work_order_id"), "core_return_items", ["work_order_id"], unique=False)
    op.create_table(
        "part_reservations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("inventory_id", sa.UUID(), nullable=False),
        sa.Column("quote_id", sa.UUID(), nullable=True),
        sa.Column("work_order_id", sa.UUID(), nullable=True),
        sa.Column("quantity_reserved", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["inventory_id"],
            ["spare_parts_inventory.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["workshop_quotes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"],
            ["work_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_part_reservations_inventory_id"), "part_reservations", ["inventory_id"], unique=False)
    op.create_index(op.f("ix_part_reservations_quote_id"), "part_reservations", ["quote_id"], unique=False)
    op.create_index(op.f("ix_part_reservations_status"), "part_reservations", ["status"], unique=False)
    op.create_index(op.f("ix_part_reservations_tenant_id"), "part_reservations", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_part_reservations_work_order_id"), "part_reservations", ["work_order_id"], unique=False)
    op.create_table(
        "spare_part_requisitions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("work_order_id", sa.UUID(), nullable=False),
        sa.Column("inventory_id", sa.UUID(), nullable=False),
        sa.Column("requested_by", sa.UUID(), nullable=True),
        sa.Column("quantity_requested", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("quantity_issued", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["inventory_id"],
            ["spare_parts_inventory.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"],
            ["work_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_spare_part_requisitions_inventory_id"), "spare_part_requisitions", ["inventory_id"], unique=False
    )
    op.create_index(op.f("ix_spare_part_requisitions_status"), "spare_part_requisitions", ["status"], unique=False)
    op.create_index(
        op.f("ix_spare_part_requisitions_tenant_id"), "spare_part_requisitions", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_spare_part_requisitions_work_order_id"), "spare_part_requisitions", ["work_order_id"], unique=False
    )
    op.create_table(
        "workshop_purchase_order_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("purchase_order_id", sa.UUID(), nullable=False),
        sa.Column("inventory_id", sa.UUID(), nullable=False),
        sa.Column("quantity_ordered", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("quantity_received", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["inventory_id"],
            ["spare_parts_inventory.id"],
        ),
        sa.ForeignKeyConstraint(["purchase_order_id"], ["workshop_purchase_orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workshop_purchase_order_items_inventory_id"),
        "workshop_purchase_order_items",
        ["inventory_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workshop_purchase_order_items_purchase_order_id"),
        "workshop_purchase_order_items",
        ["purchase_order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workshop_purchase_order_items_tenant_id"), "workshop_purchase_order_items", ["tenant_id"], unique=False
    )
    op.add_column(
        "accounting_journal_entries",
        sa.Column("journal_type", sa.String(length=10), server_default="OD", nullable=False),
    )
    op.alter_column("accounting_journal_entries", "journal_type", server_default=None)
    op.alter_column("billing_items", "trip_id", existing_type=sa.UUID(), nullable=True)
    op.add_column(
        "driver_advances",
        sa.Column("allowance_mzn", sa.Numeric(precision=10, scale=2), server_default="0.00", nullable=False),
    )
    op.add_column(
        "driver_advances",
        sa.Column("expenses_mzn", sa.Numeric(precision=10, scale=2), server_default="0.00", nullable=False),
    )
    op.create_index(
        op.f("ix_driver_advances_request_reference"), "driver_advances", ["request_reference"], unique=False
    )
    op.add_column("maintenance_plans", sa.Column("service_catalog_item_id", sa.UUID(), nullable=True))
    op.alter_column("maintenance_plans", "vehicle_id", existing_type=sa.UUID(), nullable=True)
    op.create_index(
        op.f("ix_maintenance_plans_service_catalog_item_id"),
        "maintenance_plans",
        ["service_catalog_item_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_maintenance_plans_service_catalog_item",
        "maintenance_plans",
        "service_catalog_items",
        ["service_catalog_item_id"],
        ["id"],
    )
    op.add_column("maintenance_schedule", sa.Column("quote_id", sa.UUID(), nullable=True))
    op.add_column("maintenance_schedule", sa.Column("work_order_id", sa.UUID(), nullable=True))
    op.add_column("maintenance_schedule", sa.Column("notified_due_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("maintenance_schedule", sa.Column("notified_overdue_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_maintenance_schedule_quote_id"), "maintenance_schedule", ["quote_id"], unique=False)
    op.create_index(
        op.f("ix_maintenance_schedule_work_order_id"), "maintenance_schedule", ["work_order_id"], unique=False
    )
    op.create_foreign_key(
        "fk_maintenance_schedule_work_order",
        "maintenance_schedule",
        "work_orders",
        ["work_order_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_maintenance_schedule_quote",
        "maintenance_schedule",
        "workshop_quotes",
        ["quote_id"],
        ["id"],
    )
    op.add_column("vehicle_receptions", sa.Column("assigned_work_bay_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_vehicle_receptions_assigned_work_bay_id"), "vehicle_receptions", ["assigned_work_bay_id"], unique=False
    )
    op.create_foreign_key(
        "fk_vehicle_receptions_assigned_work_bay",
        "vehicle_receptions",
        "work_bays",
        ["assigned_work_bay_id"],
        ["id"],
    )
    op.add_column("work_orders", sa.Column("work_bay_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_work_orders_work_bay_id"), "work_orders", ["work_bay_id"], unique=False)
    op.create_foreign_key(
        "fk_work_orders_work_bay",
        "work_orders",
        "work_bays",
        ["work_bay_id"],
        ["id"],
    )
    op.add_column("workshop_quotes", sa.Column("evidence_photo_file_id", sa.UUID(), nullable=True))
    op.add_column("workshop_quotes", sa.Column("acceptance_channel", sa.String(length=30), nullable=True))
    op.add_column("workshop_quotes", sa.Column("accepted_by_person_name", sa.String(length=160), nullable=True))
    op.create_foreign_key(
        "fk_workshop_quotes_evidence_photo_file",
        "workshop_quotes",
        "files",
        ["evidence_photo_file_id"],
        ["id"],
    )
    op.alter_column(
        "workshop_staff_rates",
        "hourly_rate",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Numeric(precision=14, scale=2),
        existing_nullable=False,
    )

    # Reconcile database-enforced state contracts with the implemented workshop lifecycle.
    op.drop_constraint("chk_work_orders_status", "work_orders", type_="check")
    op.create_check_constraint(
        "chk_work_orders_status",
        "work_orders",
        "status IN ('draft', 'approved', 'in_progress', 'quality_check', 'completed', 'closed', 'cancelled')",
    )
    op.drop_constraint("chk_work_order_tasks_status", "work_order_tasks", type_="check")
    op.create_check_constraint(
        "chk_work_order_tasks_status",
        "work_order_tasks",
        "status IN ('pending', 'in_progress', 'completed', 'cancelled')",
    )
    op.drop_constraint("chk_maintenance_schedule_status", "maintenance_schedule", type_="check")
    op.create_check_constraint(
        "chk_maintenance_schedule_status",
        "maintenance_schedule",
        "status IN ('pending', 'due', 'overdue', 'converted_to_wo', 'converted_to_quote', 'completed', 'cancelled')",
    )
    op.drop_constraint(
        "uq_maintenance_schedule_tenant_plan_status",
        "maintenance_schedule",
        type_="unique",
    )
    op.create_unique_constraint(
        "uq_maintenance_schedule_tenant_plan_vehicle_status",
        "maintenance_schedule",
        ["tenant_id", "plan_id", "vehicle_id", "status"],
    )
    op.drop_constraint("chk_maintenance_plans_interval", "maintenance_plans", type_="check")
    op.create_check_constraint(
        "chk_maintenance_plans_interval",
        "maintenance_plans",
        "interval_km IS NOT NULL OR interval_days IS NOT NULL OR service_catalog_item_id IS NOT NULL",
    )
    for table in _RLS_TABLES:
        _apply_canonical_rls(table)
    # ### end Alembic commands ###


def downgrade() -> None:
    for table in reversed(_RLS_TABLES):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        if table not in _ALREADY_RLS:
            op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
            op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    op.drop_constraint("chk_maintenance_plans_interval", "maintenance_plans", type_="check")
    op.create_check_constraint(
        "chk_maintenance_plans_interval",
        "maintenance_plans",
        "interval_km IS NOT NULL OR interval_days IS NOT NULL",
    )
    op.drop_constraint(
        "uq_maintenance_schedule_tenant_plan_vehicle_status",
        "maintenance_schedule",
        type_="unique",
    )
    op.create_unique_constraint(
        "uq_maintenance_schedule_tenant_plan_status",
        "maintenance_schedule",
        ["tenant_id", "plan_id", "status"],
    )
    op.drop_constraint("chk_maintenance_schedule_status", "maintenance_schedule", type_="check")
    op.create_check_constraint(
        "chk_maintenance_schedule_status",
        "maintenance_schedule",
        "status IN ('overdue', 'completed', 'cancelled', 'pending')",
    )
    op.drop_constraint("chk_work_order_tasks_status", "work_order_tasks", type_="check")
    op.create_check_constraint(
        "chk_work_order_tasks_status",
        "work_order_tasks",
        "status IN ('pending', 'completed', 'cancelled')",
    )
    op.drop_constraint("chk_work_orders_status", "work_orders", type_="check")
    op.create_check_constraint(
        "chk_work_orders_status",
        "work_orders",
        "status IN ('draft', 'approved', 'in_progress', 'quality_check', 'closed', 'cancelled')",
    )

    op.alter_column(
        "workshop_staff_rates",
        "hourly_rate",
        existing_type=sa.Numeric(precision=14, scale=2),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=False,
    )

    op.drop_constraint("fk_workshop_quotes_evidence_photo_file", "workshop_quotes", type_="foreignkey")
    op.drop_column("workshop_quotes", "accepted_by_person_name")
    op.drop_column("workshop_quotes", "acceptance_channel")
    op.drop_column("workshop_quotes", "evidence_photo_file_id")

    op.drop_constraint("fk_work_orders_work_bay", "work_orders", type_="foreignkey")
    op.drop_index(op.f("ix_work_orders_work_bay_id"), table_name="work_orders")
    op.drop_column("work_orders", "work_bay_id")

    op.drop_constraint("fk_vehicle_receptions_assigned_work_bay", "vehicle_receptions", type_="foreignkey")
    op.drop_index(op.f("ix_vehicle_receptions_assigned_work_bay_id"), table_name="vehicle_receptions")
    op.drop_column("vehicle_receptions", "assigned_work_bay_id")

    op.drop_constraint("fk_maintenance_schedule_quote", "maintenance_schedule", type_="foreignkey")
    op.drop_constraint("fk_maintenance_schedule_work_order", "maintenance_schedule", type_="foreignkey")
    op.drop_index(op.f("ix_maintenance_schedule_work_order_id"), table_name="maintenance_schedule")
    op.drop_index(op.f("ix_maintenance_schedule_quote_id"), table_name="maintenance_schedule")
    op.drop_column("maintenance_schedule", "notified_overdue_at")
    op.drop_column("maintenance_schedule", "notified_due_at")
    op.drop_column("maintenance_schedule", "work_order_id")
    op.drop_column("maintenance_schedule", "quote_id")

    op.drop_constraint("fk_maintenance_plans_service_catalog_item", "maintenance_plans", type_="foreignkey")
    op.drop_index(op.f("ix_maintenance_plans_service_catalog_item_id"), table_name="maintenance_plans")
    op.alter_column("maintenance_plans", "vehicle_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("maintenance_plans", "service_catalog_item_id")

    op.drop_index(op.f("ix_driver_advances_request_reference"), table_name="driver_advances")
    op.drop_column("driver_advances", "expenses_mzn")
    op.drop_column("driver_advances", "allowance_mzn")
    op.alter_column("billing_items", "trip_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("accounting_journal_entries", "journal_type")

    op.drop_table("workshop_purchase_order_items")
    op.drop_table("spare_part_requisitions")
    op.drop_table("part_reservations")
    op.drop_table("core_return_items")
    op.drop_table("workshop_purchase_orders")
    op.drop_table("task_labor_logs")
