"""Add governance_case_id to WorkOrder

Revision ID: 242a7399301b
Revises: 44ea755dd978
Create Date: 2026-06-27 18:49:32.536832+02:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '242a7399301b'
down_revision: str | None = '44ea755dd978'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_orders', sa.Column('governance_case_id', sa.UUID(), nullable=True))
    op.alter_column('work_orders', 'vehicle_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_work_orders_governance_case_id'), 'work_orders', ['governance_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_orders_governance_case_id'), table_name='work_orders')
    op.alter_column('work_orders', 'vehicle_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('work_orders', 'governance_case_id')
    # ### end Alembic commands ###
