"""Add MaintenanceRequestNote

Revision ID: 44ea755dd978
Revises: 59b4ff8cbb9b
Create Date: 2026-06-27 16:20:18.752463+02:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '44ea755dd978'
down_revision: str | None = '59b4ff8cbb9b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_request_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('maintenance_request_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['maintenance_request_id'], ['maintenance_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_request_notes_maintenance_request_id'), 'maintenance_request_notes', ['maintenance_request_id'], unique=False)
    op.create_index(op.f('ix_maintenance_request_notes_tenant_id'), 'maintenance_request_notes', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_request_notes_tenant_id'), table_name='maintenance_request_notes')
    op.drop_index(op.f('ix_maintenance_request_notes_maintenance_request_id'), table_name='maintenance_request_notes')
    op.drop_table('maintenance_request_notes')
    # ### end Alembic commands ###
