"""refine_delivery_proof_and_load_permit

Revision ID: 6278288d5cd8
Revises: 813e78af3d00
Create Date: 2026-05-29 22:12:53.813148+02:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "6278288d5cd8"
down_revision: str | None = "813e78af3d00"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("delivery_proofs", sa.Column("load_permit_id", sa.UUID(), nullable=True))
    op.add_column(
        "delivery_proofs", sa.Column("load_permit_number", sa.String(length=120), nullable=True)
    )
    op.add_column("delivery_proofs", sa.Column("proof_type", sa.String(length=50), nullable=False))
    op.add_column("delivery_proofs", sa.Column("client_type", sa.String(length=30), nullable=False))
    op.add_column(
        "delivery_proofs", sa.Column("validation_method", sa.String(length=50), nullable=True)
    )
    op.create_index(
        op.f("ix_delivery_proofs_load_permit_number"),
        "delivery_proofs",
        ["load_permit_number"],
        unique=False,
    )
    op.create_foreign_key(None, "delivery_proofs", "load_permits", ["load_permit_id"], ["id"])
    op.add_column("load_permits", sa.Column("issuer_type", sa.String(length=40), nullable=False))
    op.add_column("load_permits", sa.Column("issuer_name", sa.String(length=160), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("load_permits", "issuer_name")
    op.drop_column("load_permits", "issuer_type")
    op.drop_constraint(None, "delivery_proofs", type_="foreignkey")
    op.drop_index(op.f("ix_delivery_proofs_load_permit_number"), table_name="delivery_proofs")
    op.drop_column("delivery_proofs", "validation_method")
    op.drop_column("delivery_proofs", "client_type")
    op.drop_column("delivery_proofs", "proof_type")
    op.drop_column("delivery_proofs", "load_permit_number")
    op.drop_column("delivery_proofs", "load_permit_id")
    # ### end Alembic commands ###
