"""initial_schema

Revision ID: 7f978e04a63b
Revises:
Create Date: 2026-05-29 21:33:19.136067+02:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "7f978e04a63b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("plan", sa.String(length=40), nullable=False),
        sa.Column("max_vehicles", sa.Integer(), nullable=False),
        sa.Column("max_drivers", sa.Integer(), nullable=False),
        sa.Column("max_users", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_trial", sa.Boolean(), nullable=False),
        sa.Column("trial_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("whatsapp_number", sa.String(length=40), nullable=True),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=True)
    op.create_table(
        "alerts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("alert_type", sa.String(length=60), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("channel", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dismissed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alerts_alert_type"), "alerts", ["alert_type"], unique=False)
    op.create_index(op.f("ix_alerts_entity_id"), "alerts", ["entity_id"], unique=False)
    op.create_index(op.f("ix_alerts_entity_type"), "alerts", ["entity_type"], unique=False)
    op.create_index(op.f("ix_alerts_priority"), "alerts", ["priority"], unique=False)
    op.create_index(op.f("ix_alerts_status"), "alerts", ["status"], unique=False)
    op.create_index(op.f("ix_alerts_tenant_id"), "alerts", ["tenant_id"], unique=False)
    op.create_table(
        "checklist_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("type", sa.String(length=40), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("items", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_checklist_templates_tenant_id"), "checklist_templates", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_checklist_templates_type"), "checklist_templates", ["type"], unique=False
    )
    op.create_table(
        "drivers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("full_name", sa.String(length=160), nullable=False),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("emergency_contact_name", sa.String(length=160), nullable=True),
        sa.Column("emergency_contact_phone", sa.String(length=40), nullable=True),
        sa.Column("license_number", sa.String(length=80), nullable=True),
        sa.Column("license_category", sa.String(length=40), nullable=True),
        sa.Column("license_valid_until", sa.Date(), nullable=True),
        sa.Column("inatter_license", sa.String(length=80), nullable=True),
        sa.Column("inatter_valid_until", sa.Date(), nullable=True),
        sa.Column("inss_number", sa.String(length=80), nullable=True),
        sa.Column("employment_type", sa.String(length=40), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("photo_file_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["photo_file_id"], ["files.id"], name="fk_drivers_photo_file_id", use_alter=True
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_drivers_tenant_id"), "drivers", ["tenant_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=160), nullable=False),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "email", name="uq_users_tenant_email"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("driver_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("old_values", sa.JSON(), nullable=True),
        sa.Column("new_values", sa.JSON(), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_type"), "audit_logs", ["entity_type"], unique=False)
    op.create_index(op.f("ix_audit_logs_tenant_id"), "audit_logs", ["tenant_id"], unique=False)
    op.create_table(
        "driver_devices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("driver_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.String(length=160), nullable=False),
        sa.Column("device_name", sa.String(length=160), nullable=True),
        sa.Column("platform", sa.String(length=80), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_driver_devices_device_id"), "driver_devices", ["device_id"], unique=False
    )
    op.create_index(
        op.f("ix_driver_devices_driver_id"), "driver_devices", ["driver_id"], unique=False
    )
    op.create_index(
        op.f("ix_driver_devices_tenant_id"), "driver_devices", ["tenant_id"], unique=False
    )
    op.create_table(
        "driver_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("driver_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.String(length=160), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_driver_sessions_device_id"), "driver_sessions", ["device_id"], unique=False
    )
    op.create_index(
        op.f("ix_driver_sessions_driver_id"), "driver_sessions", ["driver_id"], unique=False
    )
    op.create_index(
        op.f("ix_driver_sessions_tenant_id"), "driver_sessions", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_driver_sessions_token_hash"), "driver_sessions", ["token_hash"], unique=False
    )
    op.create_table(
        "files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("file_type", sa.String(length=30), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("storage_provider", sa.String(length=40), nullable=False),
        sa.Column("mime_type", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256_hash", sa.String(length=64), nullable=False),
        sa.Column("uploaded_by_user_id", sa.UUID(), nullable=True),
        sa.Column("uploaded_by_driver_id", sa.UUID(), nullable=True),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_driver_id"],
            ["drivers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(op.f("ix_files_entity_id"), "files", ["entity_id"], unique=False)
    op.create_index(op.f("ix_files_entity_type"), "files", ["entity_type"], unique=False)
    op.create_index(op.f("ix_files_sha256_hash"), "files", ["sha256_hash"], unique=False)
    op.create_index(op.f("ix_files_tenant_id"), "files", ["tenant_id"], unique=False)
    op.create_table(
        "idempotency_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("driver_id", sa.UUID(), nullable=True),
        sa.Column("device_id", sa.String(length=160), nullable=True),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("operation", sa.String(length=60), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_body", sa.JSON(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "idempotency_key", name="uq_idempotency_tenant_key"),
    )
    op.create_index(
        op.f("ix_idempotency_keys_device_id"), "idempotency_keys", ["device_id"], unique=False
    )
    op.create_index(
        op.f("ix_idempotency_keys_driver_id"), "idempotency_keys", ["driver_id"], unique=False
    )
    op.create_index(
        op.f("ix_idempotency_keys_entity_id"), "idempotency_keys", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_idempotency_keys_entity_type"), "idempotency_keys", ["entity_type"], unique=False
    )
    op.create_index(
        op.f("ix_idempotency_keys_expires_at"), "idempotency_keys", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_idempotency_keys_idempotency_key"),
        "idempotency_keys",
        ["idempotency_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_idempotency_keys_tenant_id"), "idempotency_keys", ["tenant_id"], unique=False
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_tenant_id"), "refresh_tokens", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=False
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "sync_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("driver_id", sa.UUID(), nullable=True),
        sa.Column("device_id", sa.String(length=160), nullable=True),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("operation", sa.String(length=60), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("local_id", sa.String(length=120), nullable=True),
        sa.Column("server_id", sa.UUID(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_message", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sync_events_device_id"), "sync_events", ["device_id"], unique=False)
    op.create_index(op.f("ix_sync_events_driver_id"), "sync_events", ["driver_id"], unique=False)
    op.create_index(
        op.f("ix_sync_events_entity_type"), "sync_events", ["entity_type"], unique=False
    )
    op.create_index(
        op.f("ix_sync_events_idempotency_key"), "sync_events", ["idempotency_key"], unique=False
    )
    op.create_index(op.f("ix_sync_events_local_id"), "sync_events", ["local_id"], unique=False)
    op.create_index(op.f("ix_sync_events_server_id"), "sync_events", ["server_id"], unique=False)
    op.create_index(op.f("ix_sync_events_status"), "sync_events", ["status"], unique=False)
    op.create_index(op.f("ix_sync_events_tenant_id"), "sync_events", ["tenant_id"], unique=False)
    op.create_table(
        "billing_documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("client_name", sa.String(length=160), nullable=False),
        sa.Column("contract_reference", sa.String(length=120), nullable=True),
        sa.Column("billing_period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("billing_period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("file_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_billing_documents_billing_period_end"),
        "billing_documents",
        ["billing_period_end"],
        unique=False,
    )
    op.create_index(
        op.f("ix_billing_documents_billing_period_start"),
        "billing_documents",
        ["billing_period_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_billing_documents_client_name"), "billing_documents", ["client_name"], unique=False
    )
    op.create_index(
        op.f("ix_billing_documents_contract_reference"),
        "billing_documents",
        ["contract_reference"],
        unique=False,
    )
    op.create_index(
        op.f("ix_billing_documents_status"), "billing_documents", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_billing_documents_tenant_id"), "billing_documents", ["tenant_id"], unique=False
    )
    op.create_table(
        "vehicles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("plate", sa.String(length=40), nullable=False),
        sa.Column("chassis", sa.String(length=80), nullable=True),
        sa.Column("brand", sa.String(length=80), nullable=True),
        sa.Column("model", sa.String(length=80), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("color", sa.String(length=40), nullable=True),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("current_km", sa.Integer(), nullable=False),
        sa.Column("fuel_type", sa.String(length=30), nullable=False),
        sa.Column("documents", sa.JSON(), nullable=True),
        sa.Column("qr_code_hash", sa.String(length=255), nullable=True),
        sa.Column("photo_file_id", sa.UUID(), nullable=True),
        sa.Column("avg_consumption_target", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("fuel_limit_daily", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["photo_file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "plate", name="uq_vehicles_tenant_plate"),
    )
    op.create_index(op.f("ix_vehicles_plate"), "vehicles", ["plate"], unique=False)
    op.create_index(op.f("ix_vehicles_qr_code_hash"), "vehicles", ["qr_code_hash"], unique=False)
    op.create_index(op.f("ix_vehicles_tenant_id"), "vehicles", ["tenant_id"], unique=False)
    op.create_table(
        "checklists",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("vehicle_id", sa.UUID(), nullable=False),
        sa.Column("driver_id", sa.UUID(), nullable=False),
        sa.Column("template_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("responses", sa.JSON(), nullable=False),
        sa.Column("location", sa.JSON(), nullable=True),
        sa.Column("gps_accuracy_m", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("gps_source", sa.String(length=40), nullable=True),
        sa.Column("client_captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "server_received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("signature_file_id", sa.UUID(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["signature_file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["checklist_templates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_checklists_driver_id"), "checklists", ["driver_id"], unique=False)
    op.create_index(op.f("ix_checklists_status"), "checklists", ["status"], unique=False)
    op.create_index(op.f("ix_checklists_tenant_id"), "checklists", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_checklists_type"), "checklists", ["type"], unique=False)
    op.create_index(op.f("ix_checklists_vehicle_id"), "checklists", ["vehicle_id"], unique=False)
    op.create_table(
        "fuel_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("vehicle_id", sa.UUID(), nullable=False),
        sa.Column("driver_id", sa.UUID(), nullable=False),
        sa.Column("fuel_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("station_name", sa.String(length=160), nullable=True),
        sa.Column("station_location", sa.JSON(), nullable=True),
        sa.Column("fuel_type", sa.String(length=30), nullable=False),
        sa.Column("liters", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("price_per_liter", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("total_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("km_at_refuel", sa.Integer(), nullable=False),
        sa.Column("km_since_last", sa.Integer(), nullable=True),
        sa.Column("consumption_l_per_100km", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("receipt_file_id", sa.UUID(), nullable=True),
        sa.Column("odometer_file_id", sa.UUID(), nullable=True),
        sa.Column("payment_method", sa.String(length=60), nullable=True),
        sa.Column("payment_reference", sa.String(length=120), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("verified_by_user_id", sa.UUID(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("flagged", sa.Boolean(), nullable=False),
        sa.Column("client_captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "server_received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["odometer_file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["receipt_file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fuel_logs_driver_id"), "fuel_logs", ["driver_id"], unique=False)
    op.create_index(op.f("ix_fuel_logs_fuel_date"), "fuel_logs", ["fuel_date"], unique=False)
    op.create_index(op.f("ix_fuel_logs_tenant_id"), "fuel_logs", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_fuel_logs_vehicle_id"), "fuel_logs", ["vehicle_id"], unique=False)
    op.create_table(
        "trips",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("vehicle_id", sa.UUID(), nullable=False),
        sa.Column("driver_id", sa.UUID(), nullable=False),
        sa.Column("origin", sa.String(length=160), nullable=False),
        sa.Column("origin_location", sa.JSON(), nullable=True),
        sa.Column("destination", sa.String(length=160), nullable=False),
        sa.Column("destination_location", sa.JSON(), nullable=True),
        sa.Column("cargo_type", sa.String(length=120), nullable=True),
        sa.Column("cargo_class", sa.String(length=40), nullable=True),
        sa.Column("cargo_weight", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("cargo_volume", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("cargo_volumes", sa.Integer(), nullable=True),
        sa.Column("cargo_file_id", sa.UUID(), nullable=True),
        sa.Column("load_state", sa.String(length=40), nullable=True),
        sa.Column("requires_load_permit", sa.Boolean(), nullable=False),
        sa.Column("requires_cargo_manifest", sa.Boolean(), nullable=False),
        sa.Column("waybill_number", sa.String(length=120), nullable=True),
        sa.Column("km_start", sa.Integer(), nullable=True),
        sa.Column("km_start_file_id", sa.UUID(), nullable=True),
        sa.Column("km_end", sa.Integer(), nullable=True),
        sa.Column("km_end_file_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("planned_departure", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_departure", sa.DateTime(timezone=True), nullable=True),
        sa.Column("planned_arrival", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_arrival", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recipient_name", sa.String(length=160), nullable=True),
        sa.Column("recipient_signature_file_id", sa.UUID(), nullable=True),
        sa.Column("delivery_file_id", sa.UUID(), nullable=True),
        sa.Column("cargo_status", sa.String(length=40), nullable=True),
        sa.Column("total_fuel_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total_expense_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total_transport_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("contract_reference", sa.String(length=120), nullable=True),
        sa.Column("billing_status", sa.String(length=40), nullable=False),
        sa.Column("billable_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("billed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("billing_document_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["billing_document_id"],
            ["billing_documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cargo_file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["delivery_file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["km_end_file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["km_start_file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipient_signature_file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trips_billing_status"), "trips", ["billing_status"], unique=False)
    op.create_index(
        op.f("ix_trips_contract_reference"), "trips", ["contract_reference"], unique=False
    )
    op.create_index(op.f("ix_trips_driver_id"), "trips", ["driver_id"], unique=False)
    op.create_index(op.f("ix_trips_status"), "trips", ["status"], unique=False)
    op.create_index(op.f("ix_trips_tenant_id"), "trips", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_trips_vehicle_id"), "trips", ["vehicle_id"], unique=False)
    op.create_table(
        "cargo_manifests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("trip_id", sa.UUID(), nullable=False),
        sa.Column("manifest_number", sa.String(length=120), nullable=True),
        sa.Column("issuer_user_id", sa.UUID(), nullable=True),
        sa.Column("client_name", sa.String(length=160), nullable=True),
        sa.Column("shipper_name", sa.String(length=160), nullable=True),
        sa.Column("recipient_name", sa.String(length=160), nullable=True),
        sa.Column("cargo_description", sa.Text(), nullable=True),
        sa.Column("cargo_type", sa.String(length=120), nullable=True),
        sa.Column("cargo_class", sa.String(length=40), nullable=True),
        sa.Column("package_count", sa.Integer(), nullable=True),
        sa.Column("gross_weight", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("origin", sa.String(length=160), nullable=True),
        sa.Column("destination", sa.String(length=160), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("file_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["issuer_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cargo_manifests_manifest_number"),
        "cargo_manifests",
        ["manifest_number"],
        unique=False,
    )
    op.create_index(op.f("ix_cargo_manifests_status"), "cargo_manifests", ["status"], unique=False)
    op.create_index(
        op.f("ix_cargo_manifests_tenant_id"), "cargo_manifests", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_cargo_manifests_trip_id"), "cargo_manifests", ["trip_id"], unique=False
    )
    op.create_table(
        "delivery_proofs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("trip_id", sa.UUID(), nullable=False),
        sa.Column("document_number", sa.String(length=120), nullable=True),
        sa.Column("receiver_name", sa.String(length=160), nullable=True),
        sa.Column("receiver_contact", sa.String(length=80), nullable=True),
        sa.Column("delivery_location", sa.String(length=200), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cargo_condition", sa.String(length=30), nullable=False),
        sa.Column("quantity_delivered", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("file_id", sa.UUID(), nullable=True),
        sa.Column("created_by_driver_id", sa.UUID(), nullable=True),
        sa.Column("verified_by_user_id", sa.UUID(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_driver_id"],
            ["drivers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_delivery_proofs_delivered_at"), "delivery_proofs", ["delivered_at"], unique=False
    )
    op.create_index(
        op.f("ix_delivery_proofs_document_number"),
        "delivery_proofs",
        ["document_number"],
        unique=False,
    )
    op.create_index(op.f("ix_delivery_proofs_status"), "delivery_proofs", ["status"], unique=False)
    op.create_index(
        op.f("ix_delivery_proofs_tenant_id"), "delivery_proofs", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_delivery_proofs_trip_id"), "delivery_proofs", ["trip_id"], unique=False
    )
    op.create_table(
        "load_permits",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("trip_id", sa.UUID(), nullable=False),
        sa.Column("client_name", sa.String(length=160), nullable=True),
        sa.Column("client_reference", sa.String(length=120), nullable=True),
        sa.Column("permit_number", sa.String(length=120), nullable=True),
        sa.Column("district", sa.String(length=120), nullable=True),
        sa.Column("location_name", sa.String(length=160), nullable=True),
        sa.Column("origin", sa.String(length=160), nullable=True),
        sa.Column("destination", sa.String(length=160), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("leg_type", sa.String(length=40), nullable=False),
        sa.Column("load_state", sa.String(length=40), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_load_permits_district"), "load_permits", ["district"], unique=False)
    op.create_index(
        op.f("ix_load_permits_permit_number"), "load_permits", ["permit_number"], unique=False
    )
    op.create_index(op.f("ix_load_permits_status"), "load_permits", ["status"], unique=False)
    op.create_index(op.f("ix_load_permits_tenant_id"), "load_permits", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_load_permits_trip_id"), "load_permits", ["trip_id"], unique=False)
    op.create_table(
        "transport_documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("trip_id", sa.UUID(), nullable=False),
        sa.Column("document_type", sa.String(length=40), nullable=False),
        sa.Column("document_number", sa.String(length=120), nullable=True),
        sa.Column("issuer", sa.String(length=160), nullable=True),
        sa.Column("client_name", sa.String(length=160), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("origin", sa.String(length=160), nullable=True),
        sa.Column("destination", sa.String(length=160), nullable=True),
        sa.Column("district", sa.String(length=120), nullable=True),
        sa.Column("location_name", sa.String(length=160), nullable=True),
        sa.Column("file_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transport_documents_document_number"),
        "transport_documents",
        ["document_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transport_documents_document_type"),
        "transport_documents",
        ["document_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transport_documents_status"), "transport_documents", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_transport_documents_tenant_id"), "transport_documents", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_transport_documents_trip_id"), "transport_documents", ["trip_id"], unique=False
    )
    op.create_table(
        "trip_costs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("trip_id", sa.UUID(), nullable=False),
        sa.Column("cost_type", sa.String(length=40), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("paid_by", sa.String(length=30), nullable=False),
        sa.Column("payment_method", sa.String(length=60), nullable=True),
        sa.Column("receipt_file_id", sa.UUID(), nullable=True),
        sa.Column("incurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["receipt_file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trip_costs_cost_type"), "trip_costs", ["cost_type"], unique=False)
    op.create_index(op.f("ix_trip_costs_incurred_at"), "trip_costs", ["incurred_at"], unique=False)
    op.create_index(op.f("ix_trip_costs_tenant_id"), "trip_costs", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_trip_costs_trip_id"), "trip_costs", ["trip_id"], unique=False)
    op.create_table(
        "trip_stops",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("trip_id", sa.UUID(), nullable=False),
        sa.Column("stop_type", sa.String(length=40), nullable=False),
        sa.Column("location", sa.JSON(), nullable=True),
        sa.Column("address", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("photo_file_id", sa.UUID(), nullable=True),
        sa.Column("cost", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("expense_category", sa.String(length=60), nullable=True),
        sa.Column("stopped_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["photo_file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trip_stops_stop_type"), "trip_stops", ["stop_type"], unique=False)
    op.create_index(op.f("ix_trip_stops_stopped_at"), "trip_stops", ["stopped_at"], unique=False)
    op.create_index(op.f("ix_trip_stops_tenant_id"), "trip_stops", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_trip_stops_trip_id"), "trip_stops", ["trip_id"], unique=False)
    op.create_table(
        "billing_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("billing_document_id", sa.UUID(), nullable=False),
        sa.Column("trip_id", sa.UUID(), nullable=False),
        sa.Column("delivery_proof_id", sa.UUID(), nullable=True),
        sa.Column("client_reference", sa.String(length=120), nullable=True),
        sa.Column("origin", sa.String(length=160), nullable=True),
        sa.Column("destination", sa.String(length=160), nullable=True),
        sa.Column("district", sa.String(length=120), nullable=True),
        sa.Column("cargo_description", sa.Text(), nullable=True),
        sa.Column("cargo_class", sa.String(length=40), nullable=True),
        sa.Column("load_state", sa.String(length=40), nullable=True),
        sa.Column("loaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["billing_document_id"],
            ["billing_documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["delivery_proof_id"],
            ["delivery_proofs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_billing_items_billing_document_id"),
        "billing_items",
        ["billing_document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_billing_items_delivered_at"), "billing_items", ["delivered_at"], unique=False
    )
    op.create_index(op.f("ix_billing_items_status"), "billing_items", ["status"], unique=False)
    op.create_index(
        op.f("ix_billing_items_tenant_id"), "billing_items", ["tenant_id"], unique=False
    )
    op.create_index(op.f("ix_billing_items_trip_id"), "billing_items", ["trip_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_billing_items_trip_id"), table_name="billing_items")
    op.drop_index(op.f("ix_billing_items_tenant_id"), table_name="billing_items")
    op.drop_index(op.f("ix_billing_items_status"), table_name="billing_items")
    op.drop_index(op.f("ix_billing_items_delivered_at"), table_name="billing_items")
    op.drop_index(op.f("ix_billing_items_billing_document_id"), table_name="billing_items")
    op.drop_table("billing_items")
    op.drop_index(op.f("ix_trip_stops_trip_id"), table_name="trip_stops")
    op.drop_index(op.f("ix_trip_stops_tenant_id"), table_name="trip_stops")
    op.drop_index(op.f("ix_trip_stops_stopped_at"), table_name="trip_stops")
    op.drop_index(op.f("ix_trip_stops_stop_type"), table_name="trip_stops")
    op.drop_table("trip_stops")
    op.drop_index(op.f("ix_trip_costs_trip_id"), table_name="trip_costs")
    op.drop_index(op.f("ix_trip_costs_tenant_id"), table_name="trip_costs")
    op.drop_index(op.f("ix_trip_costs_incurred_at"), table_name="trip_costs")
    op.drop_index(op.f("ix_trip_costs_cost_type"), table_name="trip_costs")
    op.drop_table("trip_costs")
    op.drop_index(op.f("ix_transport_documents_trip_id"), table_name="transport_documents")
    op.drop_index(op.f("ix_transport_documents_tenant_id"), table_name="transport_documents")
    op.drop_index(op.f("ix_transport_documents_status"), table_name="transport_documents")
    op.drop_index(op.f("ix_transport_documents_document_type"), table_name="transport_documents")
    op.drop_index(op.f("ix_transport_documents_document_number"), table_name="transport_documents")
    op.drop_table("transport_documents")
    op.drop_index(op.f("ix_load_permits_trip_id"), table_name="load_permits")
    op.drop_index(op.f("ix_load_permits_tenant_id"), table_name="load_permits")
    op.drop_index(op.f("ix_load_permits_status"), table_name="load_permits")
    op.drop_index(op.f("ix_load_permits_permit_number"), table_name="load_permits")
    op.drop_index(op.f("ix_load_permits_district"), table_name="load_permits")
    op.drop_table("load_permits")
    op.drop_index(op.f("ix_delivery_proofs_trip_id"), table_name="delivery_proofs")
    op.drop_index(op.f("ix_delivery_proofs_tenant_id"), table_name="delivery_proofs")
    op.drop_index(op.f("ix_delivery_proofs_status"), table_name="delivery_proofs")
    op.drop_index(op.f("ix_delivery_proofs_document_number"), table_name="delivery_proofs")
    op.drop_index(op.f("ix_delivery_proofs_delivered_at"), table_name="delivery_proofs")
    op.drop_table("delivery_proofs")
    op.drop_index(op.f("ix_cargo_manifests_trip_id"), table_name="cargo_manifests")
    op.drop_index(op.f("ix_cargo_manifests_tenant_id"), table_name="cargo_manifests")
    op.drop_index(op.f("ix_cargo_manifests_status"), table_name="cargo_manifests")
    op.drop_index(op.f("ix_cargo_manifests_manifest_number"), table_name="cargo_manifests")
    op.drop_table("cargo_manifests")
    op.drop_index(op.f("ix_trips_vehicle_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_tenant_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_status"), table_name="trips")
    op.drop_index(op.f("ix_trips_driver_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_contract_reference"), table_name="trips")
    op.drop_index(op.f("ix_trips_billing_status"), table_name="trips")
    op.drop_table("trips")
    op.drop_index(op.f("ix_fuel_logs_vehicle_id"), table_name="fuel_logs")
    op.drop_index(op.f("ix_fuel_logs_tenant_id"), table_name="fuel_logs")
    op.drop_index(op.f("ix_fuel_logs_fuel_date"), table_name="fuel_logs")
    op.drop_index(op.f("ix_fuel_logs_driver_id"), table_name="fuel_logs")
    op.drop_table("fuel_logs")
    op.drop_index(op.f("ix_checklists_vehicle_id"), table_name="checklists")
    op.drop_index(op.f("ix_checklists_type"), table_name="checklists")
    op.drop_index(op.f("ix_checklists_tenant_id"), table_name="checklists")
    op.drop_index(op.f("ix_checklists_status"), table_name="checklists")
    op.drop_index(op.f("ix_checklists_driver_id"), table_name="checklists")
    op.drop_table("checklists")
    op.drop_index(op.f("ix_vehicles_tenant_id"), table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_qr_code_hash"), table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_plate"), table_name="vehicles")
    op.drop_table("vehicles")
    op.drop_index(op.f("ix_billing_documents_tenant_id"), table_name="billing_documents")
    op.drop_index(op.f("ix_billing_documents_status"), table_name="billing_documents")
    op.drop_index(op.f("ix_billing_documents_contract_reference"), table_name="billing_documents")
    op.drop_index(op.f("ix_billing_documents_client_name"), table_name="billing_documents")
    op.drop_index(op.f("ix_billing_documents_billing_period_start"), table_name="billing_documents")
    op.drop_index(op.f("ix_billing_documents_billing_period_end"), table_name="billing_documents")
    op.drop_table("billing_documents")
    op.drop_index(op.f("ix_sync_events_tenant_id"), table_name="sync_events")
    op.drop_index(op.f("ix_sync_events_status"), table_name="sync_events")
    op.drop_index(op.f("ix_sync_events_server_id"), table_name="sync_events")
    op.drop_index(op.f("ix_sync_events_local_id"), table_name="sync_events")
    op.drop_index(op.f("ix_sync_events_idempotency_key"), table_name="sync_events")
    op.drop_index(op.f("ix_sync_events_entity_type"), table_name="sync_events")
    op.drop_index(op.f("ix_sync_events_driver_id"), table_name="sync_events")
    op.drop_index(op.f("ix_sync_events_device_id"), table_name="sync_events")
    op.drop_table("sync_events")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_tenant_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_idempotency_keys_tenant_id"), table_name="idempotency_keys")
    op.drop_index(op.f("ix_idempotency_keys_idempotency_key"), table_name="idempotency_keys")
    op.drop_index(op.f("ix_idempotency_keys_expires_at"), table_name="idempotency_keys")
    op.drop_index(op.f("ix_idempotency_keys_entity_type"), table_name="idempotency_keys")
    op.drop_index(op.f("ix_idempotency_keys_entity_id"), table_name="idempotency_keys")
    op.drop_index(op.f("ix_idempotency_keys_driver_id"), table_name="idempotency_keys")
    op.drop_index(op.f("ix_idempotency_keys_device_id"), table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_index(op.f("ix_files_tenant_id"), table_name="files")
    op.drop_index(op.f("ix_files_sha256_hash"), table_name="files")
    op.drop_index(op.f("ix_files_entity_type"), table_name="files")
    op.drop_index(op.f("ix_files_entity_id"), table_name="files")
    op.drop_table("files")
    op.drop_index(op.f("ix_driver_sessions_token_hash"), table_name="driver_sessions")
    op.drop_index(op.f("ix_driver_sessions_tenant_id"), table_name="driver_sessions")
    op.drop_index(op.f("ix_driver_sessions_driver_id"), table_name="driver_sessions")
    op.drop_index(op.f("ix_driver_sessions_device_id"), table_name="driver_sessions")
    op.drop_table("driver_sessions")
    op.drop_index(op.f("ix_driver_devices_tenant_id"), table_name="driver_devices")
    op.drop_index(op.f("ix_driver_devices_driver_id"), table_name="driver_devices")
    op.drop_index(op.f("ix_driver_devices_device_id"), table_name="driver_devices")
    op.drop_table("driver_devices")
    op.drop_index(op.f("ix_audit_logs_tenant_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_drivers_tenant_id"), table_name="drivers")
    op.drop_table("drivers")
    op.drop_index(op.f("ix_checklist_templates_type"), table_name="checklist_templates")
    op.drop_index(op.f("ix_checklist_templates_tenant_id"), table_name="checklist_templates")
    op.drop_table("checklist_templates")
    op.drop_index(op.f("ix_alerts_tenant_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_status"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_priority"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_entity_type"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_entity_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_alert_type"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.drop_table("tenants")
    # ### end Alembic commands ###
