"""add_contracts

Revision ID: 813e78af3d00
Revises: 7f978e04a63b
Create Date: 2026-05-29 21:54:12.916236+02:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '813e78af3d00'
down_revision: str | None = '7f978e04a63b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('client_name', sa.String(length=160), nullable=False),
    sa.Column('contract_reference', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('service_type', sa.String(length=60), nullable=False),
    sa.Column('billing_cycle', sa.String(length=30), nullable=False),
    sa.Column('billing_basis', sa.String(length=40), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('default_unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('requires_load_permit', sa.Boolean(), nullable=False),
    sa.Column('requires_delivery_proof', sa.Boolean(), nullable=False),
    sa.Column('requires_cargo_manifest_for_manufactured_goods', sa.Boolean(), nullable=False),
    sa.Column('pricing_rules', sa.JSON(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'contract_reference', name='uq_contracts_tenant_reference')
    )
    op.create_index(op.f('ix_contracts_client_name'), 'contracts', ['client_name'], unique=False)
    op.create_index(op.f('ix_contracts_contract_reference'), 'contracts', ['contract_reference'], unique=False)
    op.create_index(op.f('ix_contracts_status'), 'contracts', ['status'], unique=False)
    op.create_index(op.f('ix_contracts_tenant_id'), 'contracts', ['tenant_id'], unique=False)
    op.add_column('billing_documents', sa.Column('contract_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_billing_documents_contract_id'), 'billing_documents', ['contract_id'], unique=False)
    op.create_foreign_key(None, 'billing_documents', 'contracts', ['contract_id'], ['id'])
    op.add_column('billing_items', sa.Column('contract_id', sa.UUID(), nullable=True))
    op.add_column('billing_items', sa.Column('load_permit_id', sa.UUID(), nullable=True))
    op.add_column('billing_items', sa.Column('cargo_manifest_id', sa.UUID(), nullable=True))
    op.add_column('billing_items', sa.Column('transport_document_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_billing_items_contract_id'), 'billing_items', ['contract_id'], unique=False)
    op.create_foreign_key(None, 'billing_items', 'transport_documents', ['transport_document_id'], ['id'])
    op.create_foreign_key(None, 'billing_items', 'load_permits', ['load_permit_id'], ['id'])
    op.create_foreign_key(None, 'billing_items', 'contracts', ['contract_id'], ['id'])
    op.create_foreign_key(None, 'billing_items', 'cargo_manifests', ['cargo_manifest_id'], ['id'])
    op.add_column('cargo_manifests', sa.Column('contract_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_cargo_manifests_contract_id'), 'cargo_manifests', ['contract_id'], unique=False)
    op.create_foreign_key(None, 'cargo_manifests', 'contracts', ['contract_id'], ['id'])
    op.add_column('delivery_proofs', sa.Column('contract_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_delivery_proofs_contract_id'), 'delivery_proofs', ['contract_id'], unique=False)
    op.create_foreign_key(None, 'delivery_proofs', 'contracts', ['contract_id'], ['id'])
    op.create_foreign_key('fk_drivers_photo_file_id', 'drivers', 'files', ['photo_file_id'], ['id'], use_alter=True)
    op.add_column('load_permits', sa.Column('contract_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_load_permits_contract_id'), 'load_permits', ['contract_id'], unique=False)
    op.create_foreign_key(None, 'load_permits', 'contracts', ['contract_id'], ['id'])
    op.add_column('transport_documents', sa.Column('contract_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_transport_documents_contract_id'), 'transport_documents', ['contract_id'], unique=False)
    op.create_foreign_key(None, 'transport_documents', 'contracts', ['contract_id'], ['id'])
    op.add_column('trips', sa.Column('contract_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_trips_contract_id'), 'trips', ['contract_id'], unique=False)
    op.create_foreign_key(None, 'trips', 'contracts', ['contract_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_index(op.f('ix_trips_contract_id'), table_name='trips')
    op.drop_column('trips', 'contract_id')
    op.drop_constraint(None, 'transport_documents', type_='foreignkey')
    op.drop_index(op.f('ix_transport_documents_contract_id'), table_name='transport_documents')
    op.drop_column('transport_documents', 'contract_id')
    op.drop_constraint(None, 'load_permits', type_='foreignkey')
    op.drop_index(op.f('ix_load_permits_contract_id'), table_name='load_permits')
    op.drop_column('load_permits', 'contract_id')
    op.drop_constraint('fk_drivers_photo_file_id', 'drivers', type_='foreignkey')
    op.drop_constraint(None, 'delivery_proofs', type_='foreignkey')
    op.drop_index(op.f('ix_delivery_proofs_contract_id'), table_name='delivery_proofs')
    op.drop_column('delivery_proofs', 'contract_id')
    op.drop_constraint(None, 'cargo_manifests', type_='foreignkey')
    op.drop_index(op.f('ix_cargo_manifests_contract_id'), table_name='cargo_manifests')
    op.drop_column('cargo_manifests', 'contract_id')
    op.drop_constraint(None, 'billing_items', type_='foreignkey')
    op.drop_constraint(None, 'billing_items', type_='foreignkey')
    op.drop_constraint(None, 'billing_items', type_='foreignkey')
    op.drop_constraint(None, 'billing_items', type_='foreignkey')
    op.drop_index(op.f('ix_billing_items_contract_id'), table_name='billing_items')
    op.drop_column('billing_items', 'transport_document_id')
    op.drop_column('billing_items', 'cargo_manifest_id')
    op.drop_column('billing_items', 'load_permit_id')
    op.drop_column('billing_items', 'contract_id')
    op.drop_constraint(None, 'billing_documents', type_='foreignkey')
    op.drop_index(op.f('ix_billing_documents_contract_id'), table_name='billing_documents')
    op.drop_column('billing_documents', 'contract_id')
    op.drop_index(op.f('ix_contracts_tenant_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_status'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_contract_reference'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_client_name'), table_name='contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
