"""add accounting check constraints

Revision ID: 92c11f6fdf9d
Revises: 95929ae669b9
Create Date: 2026-06-28 22:03:33.100092+02:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '92c11f6fdf9d'
down_revision: str | None = '95929ae669b9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('check_debit_credit_positive', 'accounting_journal_items', 'debit >= 0 AND credit >= 0')
    op.create_check_constraint('check_mutually_exclusive', 'accounting_journal_items', 'debit = 0 OR credit = 0')
    op.create_check_constraint('check_not_both_zero', 'accounting_journal_items', 'debit > 0 OR credit > 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_not_both_zero', 'accounting_journal_items', type_='check')
    op.drop_constraint('check_mutually_exclusive', 'accounting_journal_items', type_='check')
    op.drop_constraint('check_debit_credit_positive', 'accounting_journal_items', type_='check')
    # ### end Alembic commands ###
