"""Add HR and Inventory modules

Revision ID: 95929ae669b9
Revises: aaeadb9644c0
Create Date: 2026-06-28 21:18:10.609158+02:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '95929ae669b9'
down_revision: str | None = 'aaeadb9644c0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
