"""add_accounting_models

Revision ID: aaeadb9644c0
Revises: ceddc8a708f9
Create Date: 2026-06-27 20:44:33.771464+02:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'aaeadb9644c0'
down_revision: str | None = 'ceddc8a708f9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['accounting_accounts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_accounting_accounts_tenant_code', 'accounting_accounts', ['tenant_id', 'code'], unique=True)
    op.create_index(op.f('ix_accounting_accounts_tenant_id'), 'accounting_accounts', ['tenant_id'], unique=False)
    op.create_table('accounting_journal_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_document_type', sa.String(length=100), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_accounting_journal_entries_tenant_date', 'accounting_journal_entries', ['tenant_id', 'date'], unique=False)
    op.create_index(op.f('ix_accounting_journal_entries_tenant_id'), 'accounting_journal_entries', ['tenant_id'], unique=False)
    op.create_table('accounting_journal_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('third_party_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('work_order_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounting_accounts.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['accounting_journal_entries.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['third_party_id'], ['third_parties.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounting_journal_items_account_id'), 'accounting_journal_items', ['account_id'], unique=False)
    op.create_index(op.f('ix_accounting_journal_items_journal_entry_id'), 'accounting_journal_items', ['journal_entry_id'], unique=False)
    op.create_index(op.f('ix_accounting_journal_items_tenant_id'), 'accounting_journal_items', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_accounting_journal_items_third_party_id'), 'accounting_journal_items', ['third_party_id'], unique=False)
    op.create_index(op.f('ix_accounting_journal_items_trip_id'), 'accounting_journal_items', ['trip_id'], unique=False)
    op.create_index(op.f('ix_accounting_journal_items_vehicle_id'), 'accounting_journal_items', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_accounting_journal_items_work_order_id'), 'accounting_journal_items', ['work_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounting_journal_items_work_order_id'), table_name='accounting_journal_items')
    op.drop_index(op.f('ix_accounting_journal_items_vehicle_id'), table_name='accounting_journal_items')
    op.drop_index(op.f('ix_accounting_journal_items_trip_id'), table_name='accounting_journal_items')
    op.drop_index(op.f('ix_accounting_journal_items_third_party_id'), table_name='accounting_journal_items')
    op.drop_index(op.f('ix_accounting_journal_items_tenant_id'), table_name='accounting_journal_items')
    op.drop_index(op.f('ix_accounting_journal_items_journal_entry_id'), table_name='accounting_journal_items')
    op.drop_index(op.f('ix_accounting_journal_items_account_id'), table_name='accounting_journal_items')
    op.drop_table('accounting_journal_items')
    op.drop_index(op.f('ix_accounting_journal_entries_tenant_id'), table_name='accounting_journal_entries')
    op.drop_index('ix_accounting_journal_entries_tenant_date', table_name='accounting_journal_entries')
    op.drop_table('accounting_journal_entries')
    op.drop_index(op.f('ix_accounting_accounts_tenant_id'), table_name='accounting_accounts')
    op.drop_index('ix_accounting_accounts_tenant_code', table_name='accounting_accounts')
    op.drop_table('accounting_accounts')
    # ### end Alembic commands ###
