"""fix_schema_drift

Revision ID: acfa8ae500c0
Revises: 9a3cc9a059814
Create Date: 2026-06-19 06:39:22.205143+02:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'acfa8ae500c0'
down_revision: str | None = '9a3cc9a059814'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_billing_documents_due_date'), table_name='billing_documents')
    op.drop_index(op.f('ix_billing_documents_tenant_client_due'), table_name='billing_documents')
    op.drop_constraint(op.f('uq_billing_docs_tenant_invoice_number'), 'billing_documents', type_='unique')
    op.drop_constraint(op.f('fk_billing_documents_parent'), 'billing_documents', type_='foreignkey')
    op.create_foreign_key(None, 'billing_documents', 'billing_documents', ['parent_document_id'], ['id'])
    op.alter_column('client_payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('clients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('clients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'delivery_proofs', 'users', ['accepted_by'], ['id'])
    op.create_foreign_key(None, 'delivery_proofs', 'users', ['rejected_by'], ['id'])
    op.create_foreign_key(None, 'delivery_proofs', 'users', ['resolved_by'], ['id'])
    op.drop_index(op.f('ix_fuel_logs_tenant_created_at'), table_name='fuel_logs')
    op.drop_index(op.f('ix_fuel_logs_tenant_vehicle'), table_name='fuel_logs')
    op.drop_index(op.f('ix_maintenance_plans_tenant_status_km'), table_name='maintenance_plans')
    op.drop_index(op.f('ix_maintenance_schedule_tenant_status'), table_name='maintenance_schedule')
    op.alter_column('payment_allocations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_sync_events_tenant_driver'), table_name='sync_events')
    op.create_foreign_key(None, 'trip_orders', 'users', ['rejected_by'], ['id'])
    op.drop_index(op.f('ix_trip_stops_tenant_trip'), table_name='trip_stops')
    op.drop_index(op.f('ix_trips_tenant_actual_departure'), table_name='trips')
    op.drop_index(op.f('ix_trips_tenant_driver_status'), table_name='trips')
    op.drop_index(op.f('ix_trips_tenant_status'), table_name='trips')
    op.drop_index(op.f('ix_trips_tenant_vehicle_status'), table_name='trips')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_trips_tenant_vehicle_status'), 'trips', ['tenant_id', 'vehicle_id', 'status'], unique=False)
    op.create_index(op.f('ix_trips_tenant_status'), 'trips', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_trips_tenant_driver_status'), 'trips', ['tenant_id', 'driver_id', 'status'], unique=False)
    op.create_index(op.f('ix_trips_tenant_actual_departure'), 'trips', ['tenant_id', 'actual_departure'], unique=False)
    op.create_index(op.f('ix_trip_stops_tenant_trip'), 'trip_stops', ['tenant_id', 'trip_id'], unique=False)
    op.drop_constraint(None, 'trip_orders', type_='foreignkey')
    op.create_index(op.f('ix_sync_events_tenant_driver'), 'sync_events', ['tenant_id', 'driver_id'], unique=False)
    op.alter_column('payment_allocations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_maintenance_schedule_tenant_status'), 'maintenance_schedule', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_maintenance_plans_tenant_status_km'), 'maintenance_plans', ['tenant_id', 'status', 'next_due_km'], unique=False)
    op.create_index(op.f('ix_fuel_logs_tenant_vehicle'), 'fuel_logs', ['tenant_id', 'vehicle_id'], unique=False)
    op.create_index(op.f('ix_fuel_logs_tenant_created_at'), 'fuel_logs', ['tenant_id', 'created_at'], unique=False)
    op.drop_constraint(None, 'delivery_proofs', type_='foreignkey')
    op.drop_constraint(None, 'delivery_proofs', type_='foreignkey')
    op.drop_constraint(None, 'delivery_proofs', type_='foreignkey')
    op.alter_column('clients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('clients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'billing_documents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_billing_documents_parent'), 'billing_documents', 'billing_documents', ['parent_document_id'], ['id'], ondelete='RESTRICT')
    op.create_unique_constraint(op.f('uq_billing_docs_tenant_invoice_number'), 'billing_documents', ['tenant_id', 'invoice_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_billing_documents_tenant_client_due'), 'billing_documents', ['tenant_id', 'client_id', 'due_date'], unique=False)
    op.create_index(op.f('ix_billing_documents_due_date'), 'billing_documents', ['due_date'], unique=False)
    # ### end Alembic commands ###
