"""add_vehicle_trip_fks_to_payables

Revision ID: ceddc8a708f9
Revises: e800073e1feb
Create Date: 2026-06-27 20:34:13.715364+02:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ceddc8a708f9'
down_revision: str | None = 'e800073e1feb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('purchase_orders', sa.Column('vehicle_id', sa.UUID(), nullable=True))
    op.add_column('purchase_orders', sa.Column('trip_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_purchase_orders_trip_id'), 'purchase_orders', ['trip_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_vehicle_id'), 'purchase_orders', ['vehicle_id'], unique=False)
    op.create_foreign_key(None, 'purchase_orders', 'vehicles', ['vehicle_id'], ['id'])
    op.create_foreign_key(None, 'purchase_orders', 'trips', ['trip_id'], ['id'])
    op.add_column('supplier_invoices', sa.Column('vehicle_id', sa.UUID(), nullable=True))
    op.add_column('supplier_invoices', sa.Column('trip_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_supplier_invoices_trip_id'), 'supplier_invoices', ['trip_id'], unique=False)
    op.create_index(op.f('ix_supplier_invoices_vehicle_id'), 'supplier_invoices', ['vehicle_id'], unique=False)
    op.create_foreign_key(None, 'supplier_invoices', 'trips', ['trip_id'], ['id'])
    op.create_foreign_key(None, 'supplier_invoices', 'vehicles', ['vehicle_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supplier_invoices', type_='foreignkey')
    op.drop_constraint(None, 'supplier_invoices', type_='foreignkey')
    op.drop_index(op.f('ix_supplier_invoices_vehicle_id'), table_name='supplier_invoices')
    op.drop_index(op.f('ix_supplier_invoices_trip_id'), table_name='supplier_invoices')
    op.drop_column('supplier_invoices', 'trip_id')
    op.drop_column('supplier_invoices', 'vehicle_id')
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_orders_vehicle_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_trip_id'), table_name='purchase_orders')
    op.drop_column('purchase_orders', 'trip_id')
    op.drop_column('purchase_orders', 'vehicle_id')
    # ### end Alembic commands ###
