"""add_payables_models

Revision ID: e800073e1feb
Revises: 7933d20ec33b
Create Date: 2026-06-27 19:57:55.429037+02:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e800073e1feb'
down_revision: str | None = '7933d20ec33b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('third_party_id', sa.UUID(), nullable=False),
    sa.Column('work_order_id', sa.UUID(), nullable=True),
    sa.Column('po_number', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('estimated_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['third_party_id'], ['third_parties.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_tenant_id'), 'purchase_orders', ['tenant_id'], unique=False)
    op.create_index('ix_purchase_orders_tenant_third_party', 'purchase_orders', ['tenant_id', 'third_party_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_third_party_id'), 'purchase_orders', ['third_party_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_work_order_id'), 'purchase_orders', ['work_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_last_position_tenant_id'), table_name='vehicle_last_position')
    op.create_index(op.f('ix_vehicle_last_position_tenant'), 'vehicle_last_position', ['tenant_id'], unique=False)
    op.alter_column('vehicle_insurances', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vehicle_insurances', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_trips_tenant_vehicle_status'), 'trips', ['tenant_id', 'vehicle_id', 'status'], unique=False)
    op.create_index(op.f('ix_trips_tenant_status'), 'trips', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_trips_tenant_driver_status'), 'trips', ['tenant_id', 'driver_id', 'status'], unique=False)
    op.create_index(op.f('ix_trips_tenant_actual_departure'), 'trips', ['tenant_id', 'actual_departure'], unique=False)
    op.create_index(op.f('ix_trip_stops_tenant_trip'), 'trip_stops', ['tenant_id', 'trip_id'], unique=False)
    op.alter_column('tenant_document_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenant_document_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_sync_events_tenant_driver'), 'sync_events', ['tenant_id', 'driver_id'], unique=False)
    op.create_index(op.f('ix_sle_currency'), 'supplier_ledger_entries', ['tenant_id', 'third_party_id', 'currency'], unique=False)
    op.create_index(op.f('ix_platform_users_email'), 'platform_users', ['email'], unique=True)
    op.create_index(op.f('ix_platform_audit_logs_target_tenant_id'), 'platform_audit_logs', ['target_tenant_id'], unique=False)
    op.create_index(op.f('ix_platform_audit_logs_actor_id'), 'platform_audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_maintenance_schedule_tenant_status'), 'maintenance_schedule', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_maintenance_plans_tenant_status_km'), 'maintenance_plans', ['tenant_id', 'status', 'next_due_km'], unique=False)
    op.drop_constraint(None, 'insurance_claims', type_='foreignkey')
    op.drop_constraint(None, 'insurance_claims', type_='foreignkey')
    op.create_foreign_key(op.f('insurance_claims_incident_id_fkey'), 'insurance_claims', 'trip_incidents', ['incident_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('insurance_claims_insurance_id_fkey'), 'insurance_claims', 'vehicle_insurances', ['insurance_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_insurance_claims_status'), table_name='insurance_claims')
    op.alter_column('insurance_claims', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('insurance_claims', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_gps_positions_tenant_vehicle', table_name='gps_positions')
    op.create_index(op.f('ix_gps_positions_tenant_vehicle'), 'gps_positions', ['tenant_id', 'vehicle_id', sa.literal_column('recorded_at DESC')], unique=False)
    op.create_index(op.f('ix_fuel_logs_tenant_vehicle'), 'fuel_logs', ['tenant_id', 'vehicle_id'], unique=False)
    op.create_index(op.f('ix_fuel_logs_tenant_created_at'), 'fuel_logs', ['tenant_id', 'created_at'], unique=False)
    op.alter_column('fiscal_counters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('fiscal_counters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_driver_advances_request_reference'), table_name='driver_advances')
    op.create_table('gps_positions_2026_06',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vehicle_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('speed_kmh', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('heading_deg', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('accuracy_m', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'recorded_at', name=op.f('gps_positions_2026_06_pkey'))
    )
    op.create_index(op.f('gps_positions_2026_06_tenant_id_vehicle_id_recorded_at_idx'), 'gps_positions_2026_06', ['tenant_id', 'vehicle_id', sa.literal_column('recorded_at DESC')], unique=False)
    op.create_table('gps_positions_default',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vehicle_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('speed_kmh', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('heading_deg', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('accuracy_m', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'recorded_at', name=op.f('gps_positions_default_pkey'))
    )
    op.create_index(op.f('gps_positions_default_tenant_id_vehicle_id_recorded_at_idx'), 'gps_positions_default', ['tenant_id', 'vehicle_id', sa.literal_column('recorded_at DESC')], unique=False)
    op.create_table('gps_positions_2026_08',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vehicle_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('speed_kmh', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('heading_deg', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('accuracy_m', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'recorded_at', name=op.f('gps_positions_2026_08_pkey'))
    )
    op.create_index(op.f('gps_positions_2026_08_tenant_id_vehicle_id_recorded_at_idx'), 'gps_positions_2026_08', ['tenant_id', 'vehicle_id', sa.literal_column('recorded_at DESC')], unique=False)
    op.create_table('gps_positions_2026_07',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vehicle_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('speed_kmh', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('heading_deg', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('accuracy_m', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'recorded_at', name=op.f('gps_positions_2026_07_pkey'))
    )
    op.create_index(op.f('gps_positions_2026_07_tenant_id_vehicle_id_recorded_at_idx'), 'gps_positions_2026_07', ['tenant_id', 'vehicle_id', sa.literal_column('recorded_at DESC')], unique=False)
    op.drop_index(op.f('ix_purchase_orders_work_order_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_third_party_id'), table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_tenant_third_party', table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_tenant_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    # ### end Alembic commands ###
