"""add_known_routes

Revision ID: f8774ec1c190
Revises: e42b8f6c3a11
Create Date: 2026-06-04 21:40:48.262365+02:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "f8774ec1c190"
down_revision: str | None = "e42b8f6c3a11"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "known_routes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("origin", sa.String(length=120), nullable=False),
        sa.Column("destination", sa.String(length=120), nullable=False),
        sa.Column("distance_km", sa.Numeric(precision=10, scale=1), nullable=False),
        sa.Column("avg_fuel_liters", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "origin", "destination", name="uq_known_routes_tenant_od"),
    )
    op.create_index(op.f("ix_known_routes_tenant_id"), "known_routes", ["tenant_id"], unique=False)
    op.drop_index(op.f("idx_dispatch_clearances_trip"), table_name="dispatch_clearances")
    op.drop_index(
        op.f("idx_operational_exceptions_active_queue"), table_name="operational_exceptions"
    )
    op.drop_index(op.f("idx_operational_waivers_entity"), table_name="operational_waivers")
    op.drop_index(op.f("idx_trip_execution_events_trip_time"), table_name="trip_execution_events")
    op.drop_index(op.f("idx_trip_incidents_status"), table_name="trip_incidents")
    op.drop_index(
        op.f("idx_trip_orders_assigned_driver"),
        table_name="trip_orders",
        postgresql_where="(assigned_driver_id IS NOT NULL)",
    )
    op.drop_index(
        op.f("idx_trip_orders_assigned_vehicle"),
        table_name="trip_orders",
        postgresql_where="(assigned_vehicle_id IS NOT NULL)",
    )
    op.drop_index(op.f("idx_trip_orders_status_date"), table_name="trip_orders")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("idx_trip_orders_status_date"),
        "trip_orders",
        ["tenant_id", "status", "requested_pickup_date"],
        unique=False,
    )
    op.create_index(
        op.f("idx_trip_orders_assigned_vehicle"),
        "trip_orders",
        ["tenant_id", "assigned_vehicle_id"],
        unique=False,
        postgresql_where="(assigned_vehicle_id IS NOT NULL)",
    )
    op.create_index(
        op.f("idx_trip_orders_assigned_driver"),
        "trip_orders",
        ["tenant_id", "assigned_driver_id"],
        unique=False,
        postgresql_where="(assigned_driver_id IS NOT NULL)",
    )
    op.create_index(
        op.f("idx_trip_incidents_status"),
        "trip_incidents",
        ["tenant_id", "status", "severity"],
        unique=False,
    )
    op.create_index(
        op.f("idx_trip_execution_events_trip_time"),
        "trip_execution_events",
        ["tenant_id", "trip_id", "event_time"],
        unique=False,
    )
    op.create_index(
        op.f("idx_operational_waivers_entity"),
        "operational_waivers",
        ["tenant_id", "entity_type", "entity_id", "waiver_type", "status"],
        unique=False,
    )
    op.create_index(
        op.f("idx_operational_exceptions_active_queue"),
        "operational_exceptions",
        ["tenant_id", "status", "severity", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("idx_dispatch_clearances_trip"),
        "dispatch_clearances",
        ["tenant_id", "trip_id", "clearance_status"],
        unique=False,
    )
    op.drop_index(op.f("ix_known_routes_tenant_id"), table_name="known_routes")
    op.drop_table("known_routes")
    # ### end Alembic commands ###
